version: "3"
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - deckup-client
      - deckup-server
    networks:
      - deckup-network

  deckup-client:
    build:
      dockerfile: Dockerfile
      context: ./deckup-client
    networks:
      - deckup-network

  deckup-server:
    build:
      dockerfile: Dockerfile
      context: ./deckup-server
    env_file:
      - .env
    networks:
      - deckup-network

  networks:
    deckup-network:
      driver: bridge
