version: "3"
services:
  nginx:
    container_name: deckup-nginx
    build: .
    ports:
      - "8080:80"
    depends_on:
      - deckup-server
    networks:
      - deckup-network

  deckup-db:
    container_name: deckup-db
    image: mongo:5.0
    volumes:
      - db_data:/data/db
      - ./mongo-init-script:/docker-entrypoint-initdb.d
    networks:
      - deckup-network

  deckup-server:
    container_name: deckup-server
    build: ./deckup-server
    depends_on:
      - deckup-db
    env_file:
      - ./deckup-server/.env
    networks:
      - deckup-network

volumes:
  db_data:
    driver: local

networks:
  deckup-network:
    driver: bridge
